name: CI
on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: "1.22.0"
    - name: Vet
      run: go vet .
    - name: Build
      run: go build .
    - name: Test
      run: GODEBUG=x509sha1=1 go test -count=1 -covermode=count -coverprofile=coverage.out .
